/*
 * WaitlistAPIContractsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost8080.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for ApproveRequest type.
 */
public class ApproveRequest {
    private Integer n;
    private String featureName;

    /**
     * Default constructor.
     */
    public ApproveRequest() {
    }

    /**
     * Initialization constructor.
     * @param  n  Integer value for n.
     * @param  featureName  String value for featureName.
     */
    public ApproveRequest(
            Integer n,
            String featureName) {
        this.n = n;
        this.featureName = featureName;
    }

    /**
     * Getter for N.
     * @return Returns the Integer
     */
    @JsonGetter("n")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getN() {
        return n;
    }

    /**
     * Setter for N.
     * @param n Value for Integer
     */
    @JsonSetter("n")
    public void setN(Integer n) {
        this.n = n;
    }

    /**
     * Getter for FeatureName.
     * @return Returns the String
     */
    @JsonGetter("featureName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getFeatureName() {
        return featureName;
    }

    /**
     * Setter for FeatureName.
     * @param featureName Value for String
     */
    @JsonSetter("featureName")
    public void setFeatureName(String featureName) {
        this.featureName = featureName;
    }

    /**
     * Converts this ApproveRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ApproveRequest [" + "n=" + n + ", featureName=" + featureName + "]";
    }

    /**
     * Builds a new {@link ApproveRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ApproveRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .n(getN())
                .featureName(getFeatureName());
        return builder;
    }

    /**
     * Class to build instances of {@link ApproveRequest}.
     */
    public static class Builder {
        private Integer n;
        private String featureName;



        /**
         * Setter for n.
         * @param  n  Integer value for n.
         * @return Builder
         */
        public Builder n(Integer n) {
            this.n = n;
            return this;
        }

        /**
         * Setter for featureName.
         * @param  featureName  String value for featureName.
         * @return Builder
         */
        public Builder featureName(String featureName) {
            this.featureName = featureName;
            return this;
        }

        /**
         * Builds a new {@link ApproveRequest} object using the set fields.
         * @return {@link ApproveRequest}
         */
        public ApproveRequest build() {
            return new ApproveRequest(n, featureName);
        }
    }
}
