/*
 * WaitlistAPIContractsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost8080.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for PromoteRequest type.
 */
public class PromoteRequest {
    private String customerNumber;
    private String featureName;
    private String action;

    /**
     * Default constructor.
     */
    public PromoteRequest() {
    }

    /**
     * Initialization constructor.
     * @param  customerNumber  String value for customerNumber.
     * @param  featureName  String value for featureName.
     * @param  action  String value for action.
     */
    public PromoteRequest(
            String customerNumber,
            String featureName,
            String action) {
        this.customerNumber = customerNumber;
        this.featureName = featureName;
        this.action = action;
    }

    /**
     * Getter for CustomerNumber.
     * @return Returns the String
     */
    @JsonGetter("customerNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCustomerNumber() {
        return customerNumber;
    }

    /**
     * Setter for CustomerNumber.
     * @param customerNumber Value for String
     */
    @JsonSetter("customerNumber")
    public void setCustomerNumber(String customerNumber) {
        this.customerNumber = customerNumber;
    }

    /**
     * Getter for FeatureName.
     * @return Returns the String
     */
    @JsonGetter("featureName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getFeatureName() {
        return featureName;
    }

    /**
     * Setter for FeatureName.
     * @param featureName Value for String
     */
    @JsonSetter("featureName")
    public void setFeatureName(String featureName) {
        this.featureName = featureName;
    }

    /**
     * Getter for Action.
     * @return Returns the String
     */
    @JsonGetter("action")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAction() {
        return action;
    }

    /**
     * Setter for Action.
     * @param action Value for String
     */
    @JsonSetter("action")
    public void setAction(String action) {
        this.action = action;
    }

    /**
     * Converts this PromoteRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PromoteRequest [" + "customerNumber=" + customerNumber + ", featureName="
                + featureName + ", action=" + action + "]";
    }

    /**
     * Builds a new {@link PromoteRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PromoteRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .customerNumber(getCustomerNumber())
                .featureName(getFeatureName())
                .action(getAction());
        return builder;
    }

    /**
     * Class to build instances of {@link PromoteRequest}.
     */
    public static class Builder {
        private String customerNumber;
        private String featureName;
        private String action;



        /**
         * Setter for customerNumber.
         * @param  customerNumber  String value for customerNumber.
         * @return Builder
         */
        public Builder customerNumber(String customerNumber) {
            this.customerNumber = customerNumber;
            return this;
        }

        /**
         * Setter for featureName.
         * @param  featureName  String value for featureName.
         * @return Builder
         */
        public Builder featureName(String featureName) {
            this.featureName = featureName;
            return this;
        }

        /**
         * Setter for action.
         * @param  action  String value for action.
         * @return Builder
         */
        public Builder action(String action) {
            this.action = action;
            return this;
        }

        /**
         * Builds a new {@link PromoteRequest} object using the set fields.
         * @return {@link PromoteRequest}
         */
        public PromoteRequest build() {
            return new PromoteRequest(customerNumber, featureName, action);
        }
    }
}
