/*
 * WaitlistAPIContractsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost8080.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for WaitlistResponse type.
 */
public class WaitlistResponse {
    private String message;
    private Object data;

    /**
     * Default constructor.
     */
    public WaitlistResponse() {
    }

    /**
     * Initialization constructor.
     * @param  message  String value for message.
     * @param  data  Object value for data.
     */
    public WaitlistResponse(
            String message,
            Object data) {
        this.message = message;
        this.data = data;
    }

    /**
     * Getter for Message.
     * @return Returns the String
     */
    @JsonGetter("message")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMessage() {
        return message;
    }

    /**
     * Setter for Message.
     * @param message Value for String
     */
    @JsonSetter("message")
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * Getter for Data.
     * @return Returns the Object
     */
    @JsonGetter("data")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Object getData() {
        return data;
    }

    /**
     * Setter for Data.
     * @param data Value for Object
     */
    @JsonSetter("data")
    public void setData(Object data) {
        this.data = data;
    }

    /**
     * Converts this WaitlistResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "WaitlistResponse [" + "message=" + message + ", data=" + data + "]";
    }

    /**
     * Builds a new {@link WaitlistResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link WaitlistResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .message(getMessage())
                .data(getData());
        return builder;
    }

    /**
     * Class to build instances of {@link WaitlistResponse}.
     */
    public static class Builder {
        private String message;
        private Object data;



        /**
         * Setter for message.
         * @param  message  String value for message.
         * @return Builder
         */
        public Builder message(String message) {
            this.message = message;
            return this;
        }

        /**
         * Setter for data.
         * @param  data  Object value for data.
         * @return Builder
         */
        public Builder data(Object data) {
            this.data = data;
            return this;
        }

        /**
         * Builds a new {@link WaitlistResponse} object using the set fields.
         * @return {@link WaitlistResponse}
         */
        public WaitlistResponse build() {
            return new WaitlistResponse(message, data);
        }
    }
}
